# Default values for threshold.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

gateway:
  replicaCount: 1
  image:
    repository: threshold/gateway
    tag: latest
    pullPolicy: IfNotPresent

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

controller:
  # Determines whether the controller and its supporting objects are deployed
  enabled: true

  image:
    repository: threshold/controller
    tag: latest
    pullPolicy: IfNotPresent

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  # Change to ClusterIP if using Ingress
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - threshold-example.local
  tls: []
  #  - secretName: threshold-example-tls
  #    hosts:
  #      - threshold-example.local
